export const SET_ROLE = "SET_ROLE";

export const CREATE_CONTACT = "CREATE_CONTACT";

// rxc

export const GET_CONTACT = "GET_CONTACT";

export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const DELETE_CONTACT = "DELETE_CONTACT";

export const SELECT_CONTACT = "SELECT_CONTACT";

export const CLEAR_CONTACT = "CLEAR_CONTACT";

export const DELETE_SELECTED_CONTACTS = "DELETE_SELECTED_CONTACTS";

export const FEEDBACK_SUBMIT = "FEEDBACK_SUBMIT";

export const SET_LATITUDE = "SET_LATITUDE";

export const SET_LONGITUDE = "SET_LONGITUDE";

